---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spaceship-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "spaceship-webhook.name" . }}
    chart: {{ include "spaceship-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spaceship-webhook.fullname" . }}:access-secret
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spaceship-webhook.fullname" . }}:access-secret
  namespace: {{ .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spaceship-webhook.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ include "spaceship-webhook.fullname" . }}:access-secret
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spaceship-webhook.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: {{ include "spaceship-webhook.name" . }}
    chart: {{ include "spaceship-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "spaceship-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spaceship-webhook.fullname" . }}:auth-delegator
  labels:
    app: {{ include "spaceship-webhook.name" . }}
    chart: {{ include "spaceship-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "spaceship-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spaceship-webhook.fullname" . }}:domain-solver
  labels:
    app: {{ include "spaceship-webhook.name" . }}
    chart: {{ include "spaceship-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - "*"
    verbs:
      - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spaceship-webhook.fullname" . }}:domain-solver
  labels:
    app: {{ include "spaceship-webhook.name" . }}
    chart: {{ include "spaceship-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "spaceship-webhook.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
