---
# Source: cert-manager-webhook-spaceship/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-spaceship
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-spaceship
    chart: cert-manager-webhook-spaceship-0.1.0
    release: cert-manager-webhook-spaceship
    heritage: Helm
---
# Source: cert-manager-webhook-spaceship/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-spaceship:domain-solver
  labels:
    app: cert-manager-webhook-spaceship
    chart: cert-manager-webhook-spaceship-0.1.0
    release: cert-manager-webhook-spaceship
    heritage: Helm
rules:
  - apiGroups:
      - cert-manager-webhook-spaceship.cavetrolls.org
    resources:
      - '*'
    verbs:
      - 'create'
---
# Source: cert-manager-webhook-spaceship/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-spaceship:auth-delegator
  labels:
    app: cert-manager-webhook-spaceship
    chart: cert-manager-webhook-spaceship-0.1.0
    release: cert-manager-webhook-spaceship
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-spaceship
    namespace: cert-manager
---
# Source: cert-manager-webhook-spaceship/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-spaceship:domain-solver
  labels:
    app: cert-manager-webhook-spaceship
    chart: cert-manager-webhook-spaceship-0.1.0
    release: cert-manager-webhook-spaceship
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-spaceship:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
# Source: cert-manager-webhook-spaceship/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-spaceship:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: cert-manager-webhook-spaceship
    chart: cert-manager-webhook-spaceship-0.1.0
    release: cert-manager-webhook-spaceship
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-spaceship
    namespace: cert-manager
---
# Source: cert-manager-webhook-spaceship/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-spaceship
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-spaceship
    chart: cert-manager-webhook-spaceship-0.1.0
    release: cert-manager-webhook-spaceship
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: cert-manager-webhook-spaceship
    release: cert-manager-webhook-spaceship
---
# Source: cert-manager-webhook-spaceship/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-spaceship
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-spaceship
    chart: cert-manager-webhook-spaceship-0.1.0
    release: cert-manager-webhook-spaceship
    heritage: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app: cert-manager-webhook-spaceship
      release: cert-manager-webhook-spaceship
  template:
    metadata:
      labels:
        app: cert-manager-webhook-spaceship
        release: cert-manager-webhook-spaceship
    spec:
      serviceAccountName: cert-manager-webhook-spaceship
      containers:
        - name: cert-manager-webhook-spaceship
          image: "ghcr.io/hjwylde/cert-manager-webhook-spaceship:latest"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "cert-manager-webhook-spaceship.cavetrolls.org"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-webhook-spaceship-webhook-tls
---
# Source: cert-manager-webhook-spaceship/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.cert-manager-webhook-spaceship.cavetrolls.org
  labels:
    app: cert-manager-webhook-spaceship
    chart: cert-manager-webhook-spaceship-0.1.0
    release: cert-manager-webhook-spaceship
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/cert-manager-webhook-spaceship-webhook-tls"
spec:
  group: cert-manager-webhook-spaceship.cavetrolls.org
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-spaceship
    namespace: cert-manager
  version: v1alpha1
---
# Source: cert-manager-webhook-spaceship/templates/pki.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-spaceship-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-spaceship
    chart: cert-manager-webhook-spaceship-0.1.0
    release: cert-manager-webhook-spaceship
    heritage: Helm
spec:
  secretName: cert-manager-webhook-spaceship-ca
  duration: 43800h # 5y
  issuerRef:
    name: cert-manager-webhook-spaceship-selfsign
  commonName: "ca.spaceship-webhook.cert-manager"
  isCA: true
---
# Source: cert-manager-webhook-spaceship/templates/pki.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-spaceship-webhook-tls
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-spaceship
    chart: cert-manager-webhook-spaceship-0.1.0
    release: cert-manager-webhook-spaceship
    heritage: Helm
spec:
  secretName: cert-manager-webhook-spaceship-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: cert-manager-webhook-spaceship-ca
  dnsNames:
  - cert-manager-webhook-spaceship
  - cert-manager-webhook-spaceship.cert-manager
  - cert-manager-webhook-spaceship.cert-manager.svc
---
# Source: cert-manager-webhook-spaceship/templates/pki.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-spaceship-selfsign
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-spaceship
    chart: cert-manager-webhook-spaceship-0.1.0
    release: cert-manager-webhook-spaceship
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: cert-manager-webhook-spaceship/templates/pki.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-spaceship-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-spaceship
    chart: cert-manager-webhook-spaceship-0.1.0
    release: cert-manager-webhook-spaceship
    heritage: Helm
spec:
  ca:
    secretName: cert-manager-webhook-spaceship-ca
