---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-spaceship
  namespace: "cert-manager"
  labels:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-spaceship:domain-solver
  labels:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
rules:
  - apiGroups:
      - cert-manager-webhook-spaceship.hjwylde.github.io
    resources:
      - "*"
    verbs:
      - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-spaceship:auth-delegator
  labels:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-spaceship
    namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-spaceship:domain-solver
  labels:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-spaceship:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-webhook-spaceship:access-secret
  namespace: "cert-manager"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-webhook-spaceship:access-secret
  namespace: "cert-manager"
subjects:
  - kind: ServiceAccount
    name: cert-manager-webhook-spaceship
    namespace: "cert-manager"
roleRef:
  kind: Role
  name: cert-manager-webhook-spaceship:access-secret
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-spaceship:webhook-authentication-reader
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-spaceship
    namespace: cert-manager
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-spaceship
  namespace: "cert-manager"
  labels:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-spaceship
  namespace: "cert-manager"
  labels:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager-webhook-spaceship
      app.kubernetes.io/instance: cert-manager-webhook-spaceship
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cert-manager-webhook-spaceship
        app.kubernetes.io/instance: cert-manager-webhook-spaceship
        app.kubernetes.io/version: 0.1.3
        app.kubernetes.io/component: webhook
        app.kubernetes.io/part-of: cert-manager
    spec:
      serviceAccountName: cert-manager-webhook-spaceship
      containers:
        - name: cert-manager-webhook-spaceship
          image: "ghcr.io/hjwylde/cert-manager-webhook-spaceship:0.1.3"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "cert-manager-webhook-spaceship.hjwylde.github.io"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
            initialDelaySeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
            initialDelaySeconds: 10
            timeoutSeconds: 2
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources: {}
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-webhook-spaceship-webhook-tls
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.cert-manager-webhook-spaceship.hjwylde.github.io
  labels:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/cert-manager-webhook-spaceship-webhook-tls"
spec:
  group: cert-manager-webhook-spaceship.hjwylde.github.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-spaceship
    namespace: cert-manager
  version: v1alpha1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-spaceship-ca
  namespace: "cert-manager"
  labels:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
spec:
  secretName: cert-manager-webhook-spaceship-ca
  duration: 43800h
  issuerRef:
    name: cert-manager-webhook-spaceship-selfsign
  commonName: "ca.spaceship-webhook.cert-manager"
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-spaceship-webhook-tls
  namespace: "cert-manager"
  labels:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
spec:
  secretName: cert-manager-webhook-spaceship-webhook-tls
  duration: 8760h
  issuerRef:
    name: cert-manager-webhook-spaceship-ca
  dnsNames:
    - cert-manager-webhook-spaceship
    - cert-manager-webhook-spaceship.cert-manager
    - cert-manager-webhook-spaceship.cert-manager.svc
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-spaceship-selfsign
  namespace: "cert-manager"
  labels:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-spaceship-ca
  namespace: "cert-manager"
  labels:
    app.kubernetes.io/name: cert-manager-webhook-spaceship
    app.kubernetes.io/instance: cert-manager-webhook-spaceship
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: cert-manager
spec:
  ca:
    secretName: cert-manager-webhook-spaceship-ca
